### PR TITLE
Rework the File Explorer so its actually usable

### PR DESCRIPTION
**Pull request by NurRobin**
This PR should be used to rework the File Explorer and its implementation into the Editor so users can actually choose and edit files.

- Make Files clickable and display their content in the editor
- Add a button to upload files to the project
- Rework Visuals

### CODE REVIEW

**Comment by NurRobin** [comment]
@JonasMayerDev I think I am done with everything. If you think of something that we could add on top while reviewing, tell me.

**Comment by NurRobin** [comment]
After doing some testing I noticed that saving files broke and I should add a signal that after updating stuff like renaming, moving, or deleting files other browsers should refresh the content so they arent in an old state. Editing again..

**Comment by JonasMayerDev** [comment]
image

UI gets a little messed up with to many subfolders but functional so i will approve. Your decition if its good enough @NurRobin.

**Review by JonasMayerDev — APPROVED** [review]
Functional, see comment for ui issue.

**Comment by NurRobin** [comment]
Will work on the css a bit and then merge, thanks!

**Pull request merged**
