### PR TITLE
Delete package-lock.json

### PR DESCRIPTION
**Pull request by NurRobin**
The package-lock made difficulties when installing the project.

### CODE REVIEW

**Comment by JonasMayerDev** [comment]
That's the error I get
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: eslint-config-next@14.2.5
npm ERR! Found: eslint@9.8.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^9" from the root project
npm ERR!   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm ERR!   node_modules/@eslint-community/eslint-utils
npm ERR!     @eslint-community/eslint-utils@"^4.2.0" from eslint@9.8.0
npm ERR!   2 more (eslint-import-resolver-typescript, eslint-plugin-react)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^7.23.0 || ^8.0.0" from eslint-config-next@14.2.5
npm ERR! node_modules/eslint-config-next
npm ERR!   dev eslint-config-next@"14.2.5" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint@8.57.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^7.23.0 || ^8.0.0" from eslint-config-next@14.2.5
npm ERR!   node_modules/eslint-config-next
npm ERR!     dev eslint-config-next@"14.2.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/work/.npm/_logs/2024-08-02T12_07_59_661Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/work/.npm/_logs/2024-08-02T12_07_59_661Z-debug-0.log
```
I also solved the issue by `npm install --legacy-peer-deps` but that modified my package-lock.json. I guess we should try to find the problem behind the conflicting dependencies. Maybe we could also think about a development docker image to standardize the dev setup?

**Comment by NurRobin** [comment]
Thanks for the info. Looks like those peer dependency conflicts are the issue. Instead of adding `package-lock.json` to `.gitignore`, let's focus on fixing the root cause. We should dig into the conflicts between `eslint` and `eslint-config-next`. Also, considering Docker for a consistent dev setup sounds like a great plan. If you’re up for starting on the Docker setup, go for it.

**Comment by NurRobin** [comment]
After receiving the same error yesterday when trying to install a package, I tried working out what went wrong. After removing `eslint` and just leaving `eslint-config-next` the error vanishes. The linter still works and aside from not being 100% compatible with our TypeScript Version runs without a Problem, so… fixed, maybe?
@JonasMayerDev try running `npm uninstall eslint` and then interacting with `npm` again like installing a package or just the whole project with `npm install`.


```
> npm update --save
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: retypst@0.1.0
npm error Found: eslint@9.8.0
npm error node_modules/eslint
npm error   dev eslint@"^9" from the root project
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^7.23.0 || ^8.0.0" from eslint-config-next@14.2.5
npm error node_modules/eslint-config-next
npm error   dev eslint-config-next@"14.2.5" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\xxx\AppData\Local\npm-cache\_logs\2024-08-03T10_41_18_138Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\xxx\AppData\Local\npm-cache\_logs\2024-08-03T10_41_18_138Z-debug-0.log 

> npm uninstall eslint
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead

added 13 packages, removed 5 packages, changed 8 packages, and audited 488 packages in 12s

156 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> npm update --save   

added 14 packages, removed 11 packages, changed 7 packages, and audited 491 packages in 19s

156 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> npm install ws   

up to date, audited 491 packages in 1s

156 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> npm install eslint
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: retypst@0.1.0
npm warn Found: eslint@8.57.0
npm warn node_modules/eslint
npm warn   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm warn   node_modules/@eslint-community/eslint-utils
npm warn     @eslint-community/eslint-utils@"^4.2.0" from eslint@8.57.0
npm warn   8 more (@typescript-eslint/parser, eslint-config-next, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer eslint@"^7.23.0 || ^8.0.0" from eslint-config-next@14.2.5
npm warn node_modules/eslint-config-next
npm warn   dev eslint-config-next@"14.2.5" from the root project

up to date, audited 491 packages in 4s

156 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> npm run lint      

> retypst@0.1.0 lint
> next lint

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.5.0

YOUR TYPESCRIPT VERSION: 5.5.4

Please only submit bug reports when using the officially supported version.

=============

./app/api/v1/typst/watch/route.ts
27:1  Warning: Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

./app/editor/[id]/FileExplorer.tsx
52:6  Warning: React Hook useEffect has a missing dependency: 'fetchFiles'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./app/editor/[id]/page.tsx
162:6  Warning: React Hook useEffect has a missing dependency: 'saveFile'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
PS F:\Documents\Coding-Projekte\ReTypst> npm update --save 

added 1 package, and audited 492 packages in 20s

156 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

**Comment by NurRobin** [comment]
Installing the project on a fresh linux-distro without removing `eslint`:

```
main@ROBINS-PC:~$ git clone https://github.com/NurRobin/ReTypst.git
Cloning into 'ReTypst'...
remote: Enumerating objects: 334, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 334 (delta 59), reused 72 (delta 49), pack-reused 232
Receiving objects: 100% (334/334), 157.65 KiB | 8.76 MiB/s, done.
Resolving deltas: 100% (150/150), done.

main@ROBINS-PC:~$ sudo snap install typst
typst 0.11.1 from Martin Haug (reknih) installed

main@ROBINS-PC:~$ cd ReTypst/

main@ROBINS-PC:~/ReTypst$ npm install
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: eslint-config-next@14.2.5
npm error Found: eslint@9.8.0
npm error node_modules/eslint
npm error   dev eslint@"^9" from the root project
npm error   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm error   node_modules/@eslint-community/eslint-utils
npm error     @eslint-community/eslint-utils@"^4.2.0" from eslint@9.8.0
npm error   2 more (eslint-import-resolver-typescript, eslint-plugin-react)
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^7.23.0 || ^8.0.0" from eslint-config-next@14.2.5
npm error node_modules/eslint-config-next
npm error   dev eslint-config-next@"14.2.5" from the root project
npm error
npm error Conflicting peer dependency: eslint@8.57.0
npm error node_modules/eslint
npm error   peer eslint@"^7.23.0 || ^8.0.0" from eslint-config-next@14.2.5
npm error   node_modules/eslint-config-next
npm error     dev eslint-config-next@"14.2.5" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

After removing `eslint`:

```
main@ROBINS-PC:~$ git clone https://github.com/NurRobin/ReTypst.git
Cloning into 'ReTypst'...
remote: Enumerating objects: 334, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 334 (delta 59), reused 72 (delta 49), pack-reused 232
Receiving objects: 100% (334/334), 157.65 KiB | 9.27 MiB/s, done.
Resolving deltas: 100% (150/150), done.
main@ROBINS-PC:~$ cd ReTypst/
main@ROBINS-PC:~/ReTypst$ nano package
package-lock.json  package.json
main@ROBINS-PC:~/ReTypst$ nano package.json
main@ROBINS-PC:~/ReTypst$ nano package-lock.json
main@ROBINS-PC:~/ReTypst$ npm install
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     '\\\\wsl.localhost\\Ubuntu\\home\\main\\ReTypst\\node_modules\\level-iterator-stream',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir '\\wsl.localhost\Ubuntu\home\main\ReTypst\node_modules\level-iterator-stream\node_modules\readable-stream'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: '\\\\wsl.localhost\\Ubuntu\\home\\main\\ReTypst\\node_modules\\level-iterator-stream\\node_modules\\readable-stream'    
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]

added 465 packages, and audited 466 packages in 1m

153 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
main@ROBINS-PC:~/ReTypst$ 
```



I think that should be fine? Maybe I forgot to remove a leftover dep in `package-lock.json` but at least this seems promising.

**Comment by NurRobin** [comment]
I have committed a change I think will fix the issue. Maybe you can test it on your end and get back to me? @JonasMayerDev

**Review by JonasMayerDev — APPROVED** [review]

**Pull request merged**
